exclude: '^(.*egg.info.*|.*/parameters.py|docs/).*$'
repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --safe
        language_version: python3
-   repo: https://github.com/pycqa/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
        additional_dependencies:
          - flake8-bugbear
          - flake8-init-return == 1.0.0
